"""add new models

Revision ID: 13fac3e84d8a
Revises: c3d352627bbb
Create Date: 2022-09-11 16:31:02.924467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fac3e84d8a'
down_revision = 'c3d352627bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
