"""add new mod

Revision ID: 15a4c5ba517f
Revises: 13fac3e84d8a
Create Date: 2022-09-11 16:34:01.578102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a4c5ba517f'
down_revision = '13fac3e84d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
